name: otakustream
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Firebase Packages
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4

  #State Management & Utils
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  get: ^4.7.2
  flutter_bloc: ^9.1.0

  # UI & Animations
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  intl: ^0.20.2
  fluttertoast: ^8.2.12

  # API & Networking
  http: ^1.3.0
  dio: ^5.8.0+1
  graphql_flutter: ^5.2.0-beta.8

  # Video Streaming
  video_player: ^2.8.1
  chewie: ^1.7.0

  # UI Components
  carousel_slider: ^5.0.0
  google_sign_in: ^6.2.2
  get_storage: ^2.1.1
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.7.0
  webview_flutter: ^4.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/animations/splash_animation.json
    - assets/images/profile_bg.jpg
    - assets/images/bg.jpg
