// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoLGlxeCOg6iLSC-GOkWGcQNO9gI1W160',
    appId: '1:231965600278:web:61643406249b251e222337',
    messagingSenderId: '231965600278',
    projectId: 'otakustream-aa043',
    authDomain: 'otakustream-aa043.firebaseapp.com',
    storageBucket: 'otakustream-aa043.firebasestorage.app',
    measurementId: 'G-ZZ59115VGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwGS3qPPnD_Wr0Uep-pAOCb3lj0W5w5k0',
    appId: '1:231965600278:android:b4629404a6212f84222337',
    messagingSenderId: '231965600278',
    projectId: 'otakustream-aa043',
    storageBucket: 'otakustream-aa043.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo4m4K_NZRbTfJenngQg2ebuelNgrZdjk',
    appId: '1:231965600278:ios:606c30634b40f1c4222337',
    messagingSenderId: '231965600278',
    projectId: 'otakustream-aa043',
    storageBucket: 'otakustream-aa043.firebasestorage.app',
    iosBundleId: 'com.example.otakustream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo4m4K_NZRbTfJenngQg2ebuelNgrZdjk',
    appId: '1:231965600278:ios:606c30634b40f1c4222337',
    messagingSenderId: '231965600278',
    projectId: 'otakustream-aa043',
    storageBucket: 'otakustream-aa043.firebasestorage.app',
    iosBundleId: 'com.example.otakustream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoLGlxeCOg6iLSC-GOkWGcQNO9gI1W160',
    appId: '1:231965600278:web:3b6e217eb791877f222337',
    messagingSenderId: '231965600278',
    projectId: 'otakustream-aa043',
    authDomain: 'otakustream-aa043.firebaseapp.com',
    storageBucket: 'otakustream-aa043.firebasestorage.app',
    measurementId: 'G-4B3836WRLP',
  );
}
